name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Alter image name
        run: |-
          cd docker
          echo "RELEASE_PACKAGE=gitlab-ce
          RELEASE_VERSION=17.11.2-ce
          DOWNLOAD_URL_arm64=https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/jammy/gitlab-ce_17.11.2-ce.0_arm64.deb/download.deb
          " > RELEASE
          sed -i 's/docker.io\/ubuntu/arm64v8\/ubuntu/' Dockerfile
          
      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/gitlab:17.11.2,ghcr.io/${{ github.repository_owner }}/gitlab:latest
